# pylint configuration file

# Specify the maximum number of characters on a single line
max-line-length=120

# Enable or disable messages or categories of messages
disable:
  - C0114  # Missing module docstring
  - C0115  # Missing class docstring
  - C0116  # Missing function or method docstring

# Specify additional builtins
# (Add any built-ins your code uses regularly to avoid false positives)
generated-members=REQUEST_METHOD

# Enable/Disable certain messages
enable=unused-import,unused-variable

# Specify the output format (text, parseable, colorized, json, etc.)
output-format=text

# Add files or directories to whitelist or blacklist
# whitelist_externals=foo,bar
ignore=tests

# Specify additional directories to look for Python modules
init-hook='import sys; sys.path.append("/path/to/your/modules")'

# Specify which plugins should be enabled
plugins=pylint_django

# Django-specific configuration (if applicable)
[MASTER]
django=1

[MESSAGES CONTROL]
# Disable some Django-specific messages
disable=fixme
